apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: datasaur
  namespace: datasaur
  annotations:
    kubernetes.io/ingress.class: "kong"
    konghq.com/protocols: "https"
    konghq.com/https-redirect-status-code: "301"
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
  - secretName: hello-ts-datasaur.geeksops.com
    hosts:
    - hello-ts-datasaur.geeksops.com
  rules:
  - host: hello-ts-datasaur.geeksops.com
    http:
      paths:
      - path: /
        backend:
          serviceName: datasaur
          servicePort: 80