on:
  push:
    paths:
    - src/**
    branches:         # array of glob patterns matching against refs/heads. Optional; defaults to all
    - master          # triggers on pushes that contain changes in master

env:
  registry_hub: docker.io/rohmattriindra
  image_name: hello-ts
  cluster_name: eks-cluster-stg
  region: ap-southeast-1

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.REGION }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push the image to Docker Hub - Free ( reduce cost )
        run: |
          docker build -t ${{ env.registry_hub }}/${{ env.image_name }}:${{ github.sha }} .
          docker push ${{ env.registry_hub }}/${{ env.image_name }}:${{ github.sha }}

      - name: Set Context EKS Cluster
        run: |
          aws eks update-kubeconfig --region region --name cluster-name

      - name: Deploy Service to EKS Cluster
        uses: kodermax/kubectl-aws-eks@master
        with:
          args: apply -f deploy/manifest/deployment.yaml image=${{ env.registry_hub }}/${{ env.image_name }}::${{ github.sha }}